_index:
    pattern:  /material
    defaults: { _controller: TeachiMaterialBundle:Subject:index }

_index:
    pattern:  /material/view
    defaults: { _controller: TeachiMaterialBundle:Subject:view }

_assetic:
    resource: .
    type:     assetic